version: "3"

services:
  mysql:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql-scripts/:/docker-entrypoint-initdb.d
      - ./mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234qwer
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON